CREATE TABLE USER(
  ID INTEGER PRIMARY KEY,
  UUID TEXT UNIQUE NOT NULL,
  EMAIL TEXT NOT NULL UNIQUE,
  EXTERNAL_ID TEXT,
  PROVIDER TEXT NOT NULL,
  STATUS TEXT NOT NULL,
  DATE_CREATED TEXT NOT NULL
) STRICT;
CREATE TABLE VERSION(NUMBER INTEGER NOT NULL);
