CREATE TABLE TAPE(
  ID INTEGER PRIMARY KEY,
  TITLE TEXT NOT NULL,
  DESC TEXT,
  STATUS TEXT NOT NULL,
  DATE_CREATED TEXT NOT NULL,
  DATE_UPDATED TEXT
) STRICT;
CREATE TABLE SOURCE(
  ID INTEGER PRIMARY KEY,
  TAPE_ID INTEGER REFERENCES TAPE(ID) NOT NULL,
  SEQ INTEGER NOT NULL,
  TYPE TEXT NOT NULL,
  URL TEXT NOT NULL,
  PLAYLIST_CONTENT TEXT,
  DATE_CREATED TEXT NOT NULL,
  DATE_UPDATED TEXT
) STRICT;
