-- This file represents the schema definition of tapedeck.db in text format.
-- Once the database is in production, changes to the database will be made by adding new lines to this file.
-- Lines will never be removed from this file.
-- Only additive changes to the schema will be made, with data migrated as needed via lines in this file.
CREATE TABLE USER (ID INTEGER PRIMARY KEY, UUID TEXT UNIQUE NOT NULL, EMAIL TEXT NOT NULL UNIQUE, EXTERNAL_ID TEXT, PROVIDER TEXT NOT NULL, STATUS TEXT NOT NULL, CREATED_AT TEXT NOT NULL) STRICT;
CREATE TABLE TAPE_SOURCE (ID INTEGER PRIMARY KEY, TAPE_ID INTEGER REFERENCES TAPE (ID) NOT NULL, SEQ INTEGER NOT NULL, TYPE TEXT NOT NULL, URL TEXT NOT NULL, FILE_EXTENSION TEXT, CONTENT_TYPE TEXT, CONTENT TEXT, CREATED_AT TEXT NOT NULL, UPDATED_AT TEXT) STRICT;
CREATE TABLE STATION (ID INTEGER PRIMARY KEY, CALL_LETTERS TEXT NOT NULL, FREQ TEXT NOT NULL, DESC TEXT, HOMEPAGE_URL TEXT NOT NULL, ARCHIVES_URL TEXT, LIVE_STREAM_URL TEXT) STRICT;
CREATE TABLE TAPE (ID INTEGER PRIMARY KEY, USER_ID INTEGER REFERENCES USER (ID) NOT NULL, TITLE TEXT NOT NULL, DESC TEXT, STATION_ID INTEGER REFERENCES STATION (ID) NOT NULL, AIR_DATE TEXT NOT NULL, STATUS TEXT NOT NULL, STATUS_MSG TEXT, CREATED_AT TEXT NOT NULL, UPDATED_AT TEXT, FS_PATH TEXT NOT NULL) STRICT;
-- DB modifications go below