# This file goes to /etc/oauth2-proxy/oauth2-proxy.toml
http_address="0.0.0.0:4180"
reverse_proxy="true"
provider="google"
# This allows multiple values to it's name ends with 's'
email_domains="*"
pass_user_headers="true"
set_xauthrequest="true"
prefer_email_to_user="true"
# needed for local dev
# see https://github.com/oauth2-proxy/oauth2-proxy/issues/2949
redirect_url="http://localhost:8100/oauth2/callback"
##### DO NOT COMMIT ######
#client_id=#see secrets repo
#client_secret=#see secrets repo
#cookie_secret=#see secrets repo